

server:
  port: 9898

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/users_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
